### ISSUE TITLE
Invalid document data upload using AttachmentContent

### ISSUE THREAD

**Issue by rafaelferrari** [SAP/cloud-s4-sdk-examples#89]
Hi colleagues,

Our team is working with the attachments APIs (especifically, the `DefaultAPICVATTACHMENTSRVService` service) and we found an error with the files that were uploaded using the SDK. The operation runs fine and the document is uploaded to S/4 with the correct linked object key/type and metadata (file name, mime type); however, **the actual data for the document is not valid.** 

Through a binary comparison between the original file and the one retrieved from S/4, I've noticed that data for the uploaded file is actually readable in a text editor and it contains a JSON representation of the actual file. E.g.:

``` json
{
  "LinkedSAPObjectKey":"123456789",
  "FileSize":"39618",
  "FileName":"testfile.jpg",
  "MimeType":"image/jpeg",
  "Content":"base64encodeddatahere",
  "BusinessObjectType":"EXAMPLE"
}
```

Here is how our code looks like when creating the command (using the generated builders, we also tried to use the setter methods but we got the same result):
``` java
byte[] attachmentData = document.getDataInBytes();
AttachmentContent attachmentContent = AttachmentContent.builder()
  .attachmentContent(attachmentData)
  .fileSize(String.valueOf(attachmentData.length))
  .fileName(document.getName())
  .mimeType(document.getMimeType())
  .linkedSAPObjectKey(document.getKey())
  .businessObjectType("EXAMPLE")
  .build();
```

This `attachmentContent` variable is then provided when we call the `createAttachmentContent()` method on `DefaultAPICVATTACHMENTSRVService`, but somewhere along the way it seems like the content is being replaced with the JSON containing both the data and the metadata.

The command's `run()` method looks like this:

``` java
private Map<String, String> getUploadHeaders() {
    Map<String, String> headers = new HashMap<>();
    headers.put("Slug", attachmentContent.getFileName());
    headers.put("Content-Type", attachmentContent.getMimeType());
    headers.put("BusinessObjectTypeName", "EXAMPLE");
    headers.put("LinkedSAPObjectKey", attachmentContent.getLinkedSAPObjectKey());
    return headers;
}
...
defaultAttachmentsService
  .createAttachmentContent(attachmentContent)
  .withCustomHttpHeaders(getUploadHeaders()).onRequestAndImplicitRequests()
  .execute(getConfigContext());
```

Right now are unsure if this is caused by something we are missing from our code or if there is a bug in this service somewhere. Could you please assist us with this issue?

**Comment by MatKuhr** [comment]
Hi @rafaelferrari, let's keep the discussion on https://github.com/SAP/cloud-sdk/issues/175 since that is the recommended repo for questions & issues on the SDK in general.
